###############################################################
#  Generated by:      Cadence Innovus 20.10-p004_1
#  OS:                Linux x86_64(Host ID falcon)
#  Generated on:      Mon Jun  5 00:12:22 2023
#  Design:            AES_Composite_enc
#  Command:           create_ccopt_clock_tree_spec -file ccopt_FC.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin CLK true

# Clocks present at pin CLK
#   CLK (period 62.500ns) in timing_config AES_SDC([basasanjana/aes_up/file1.sdc])
create_ccopt_clock_tree -name CLK -source CLK -no_skew_group

# Clock period setting for source pin of CLK
set_ccopt_property clock_period -pin CLK 62.5

# Skew group to balance non generated clock:CLK in timing_config:AES_SDC (sdc basasanjana/aes_up/file1.sdc)
create_ccopt_skew_group -name CLK/AES_SDC -sources CLK -auto_sinks
set_ccopt_property include_source_latency -skew_group CLK/AES_SDC true
set_ccopt_property extracted_from_clock_name -skew_group CLK/AES_SDC CLK
set_ccopt_property extracted_from_constraint_mode_name -skew_group CLK/AES_SDC AES_SDC
set_ccopt_property extracted_from_delay_corners -skew_group CLK/AES_SDC AES_DC


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

