###################################################################

# Created by write_sdc on Sat Dec 17 14:14:07 2022

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_max_area 0
set_load -pin_load 0 [get_ports {Dout[127]}]
set_load -pin_load 0 [get_ports {Dout[126]}]
set_load -pin_load 0 [get_ports {Dout[125]}]
set_load -pin_load 0 [get_ports {Dout[124]}]
set_load -pin_load 0 [get_ports {Dout[123]}]
set_load -pin_load 0 [get_ports {Dout[122]}]
set_load -pin_load 0 [get_ports {Dout[121]}]
set_load -pin_load 0 [get_ports {Dout[120]}]
set_load -pin_load 0 [get_ports {Dout[119]}]
set_load -pin_load 0 [get_ports {Dout[118]}]
set_load -pin_load 0 [get_ports {Dout[117]}]
set_load -pin_load 0 [get_ports {Dout[116]}]
set_load -pin_load 0 [get_ports {Dout[115]}]
set_load -pin_load 0 [get_ports {Dout[114]}]
set_load -pin_load 0 [get_ports {Dout[113]}]
set_load -pin_load 0 [get_ports {Dout[112]}]
set_load -pin_load 0 [get_ports {Dout[111]}]
set_load -pin_load 0 [get_ports {Dout[110]}]
set_load -pin_load 0 [get_ports {Dout[109]}]
set_load -pin_load 0 [get_ports {Dout[108]}]
set_load -pin_load 0 [get_ports {Dout[107]}]
set_load -pin_load 0 [get_ports {Dout[106]}]
set_load -pin_load 0 [get_ports {Dout[105]}]
set_load -pin_load 0 [get_ports {Dout[104]}]
set_load -pin_load 0 [get_ports {Dout[103]}]
set_load -pin_load 0 [get_ports {Dout[102]}]
set_load -pin_load 0 [get_ports {Dout[101]}]
set_load -pin_load 0 [get_ports {Dout[100]}]
set_load -pin_load 0 [get_ports {Dout[99]}]
set_load -pin_load 0 [get_ports {Dout[98]}]
set_load -pin_load 0 [get_ports {Dout[97]}]
set_load -pin_load 0 [get_ports {Dout[96]}]
set_load -pin_load 0 [get_ports {Dout[95]}]
set_load -pin_load 0 [get_ports {Dout[94]}]
set_load -pin_load 0 [get_ports {Dout[93]}]
set_load -pin_load 0 [get_ports {Dout[92]}]
set_load -pin_load 0 [get_ports {Dout[91]}]
set_load -pin_load 0 [get_ports {Dout[90]}]
set_load -pin_load 0 [get_ports {Dout[89]}]
set_load -pin_load 0 [get_ports {Dout[88]}]
set_load -pin_load 0 [get_ports {Dout[87]}]
set_load -pin_load 0 [get_ports {Dout[86]}]
set_load -pin_load 0 [get_ports {Dout[85]}]
set_load -pin_load 0 [get_ports {Dout[84]}]
set_load -pin_load 0 [get_ports {Dout[83]}]
set_load -pin_load 0 [get_ports {Dout[82]}]
set_load -pin_load 0 [get_ports {Dout[81]}]
set_load -pin_load 0 [get_ports {Dout[80]}]
set_load -pin_load 0 [get_ports {Dout[79]}]
set_load -pin_load 0 [get_ports {Dout[78]}]
set_load -pin_load 0 [get_ports {Dout[77]}]
set_load -pin_load 0 [get_ports {Dout[76]}]
set_load -pin_load 0 [get_ports {Dout[75]}]
set_load -pin_load 0 [get_ports {Dout[74]}]
set_load -pin_load 0 [get_ports {Dout[73]}]
set_load -pin_load 0 [get_ports {Dout[72]}]
set_load -pin_load 0 [get_ports {Dout[71]}]
set_load -pin_load 0 [get_ports {Dout[70]}]
set_load -pin_load 0 [get_ports {Dout[69]}]
set_load -pin_load 0 [get_ports {Dout[68]}]
set_load -pin_load 0 [get_ports {Dout[67]}]
set_load -pin_load 0 [get_ports {Dout[66]}]
set_load -pin_load 0 [get_ports {Dout[65]}]
set_load -pin_load 0 [get_ports {Dout[64]}]
set_load -pin_load 0 [get_ports {Dout[63]}]
set_load -pin_load 0 [get_ports {Dout[62]}]
set_load -pin_load 0 [get_ports {Dout[61]}]
set_load -pin_load 0 [get_ports {Dout[60]}]
set_load -pin_load 0 [get_ports {Dout[59]}]
set_load -pin_load 0 [get_ports {Dout[58]}]
set_load -pin_load 0 [get_ports {Dout[57]}]
set_load -pin_load 0 [get_ports {Dout[56]}]
set_load -pin_load 0 [get_ports {Dout[55]}]
set_load -pin_load 0 [get_ports {Dout[54]}]
set_load -pin_load 0 [get_ports {Dout[53]}]
set_load -pin_load 0 [get_ports {Dout[52]}]
set_load -pin_load 0 [get_ports {Dout[51]}]
set_load -pin_load 0 [get_ports {Dout[50]}]
set_load -pin_load 0 [get_ports {Dout[49]}]
set_load -pin_load 0 [get_ports {Dout[48]}]
set_load -pin_load 0 [get_ports {Dout[47]}]
set_load -pin_load 0 [get_ports {Dout[46]}]
set_load -pin_load 0 [get_ports {Dout[45]}]
set_load -pin_load 0 [get_ports {Dout[44]}]
set_load -pin_load 0 [get_ports {Dout[43]}]
set_load -pin_load 0 [get_ports {Dout[42]}]
set_load -pin_load 0 [get_ports {Dout[41]}]
set_load -pin_load 0 [get_ports {Dout[40]}]
set_load -pin_load 0 [get_ports {Dout[39]}]
set_load -pin_load 0 [get_ports {Dout[38]}]
set_load -pin_load 0 [get_ports {Dout[37]}]
set_load -pin_load 0 [get_ports {Dout[36]}]
set_load -pin_load 0 [get_ports {Dout[35]}]
set_load -pin_load 0 [get_ports {Dout[34]}]
set_load -pin_load 0 [get_ports {Dout[33]}]
set_load -pin_load 0 [get_ports {Dout[32]}]
set_load -pin_load 0 [get_ports {Dout[31]}]
set_load -pin_load 0 [get_ports {Dout[30]}]
set_load -pin_load 0 [get_ports {Dout[29]}]
set_load -pin_load 0 [get_ports {Dout[28]}]
set_load -pin_load 0 [get_ports {Dout[27]}]
set_load -pin_load 0 [get_ports {Dout[26]}]
set_load -pin_load 0 [get_ports {Dout[25]}]
set_load -pin_load 0 [get_ports {Dout[24]}]
set_load -pin_load 0 [get_ports {Dout[23]}]
set_load -pin_load 0 [get_ports {Dout[22]}]
set_load -pin_load 0 [get_ports {Dout[21]}]
set_load -pin_load 0 [get_ports {Dout[20]}]
set_load -pin_load 0 [get_ports {Dout[19]}]
set_load -pin_load 0 [get_ports {Dout[18]}]
set_load -pin_load 0 [get_ports {Dout[17]}]
set_load -pin_load 0 [get_ports {Dout[16]}]
set_load -pin_load 0 [get_ports {Dout[15]}]
set_load -pin_load 0 [get_ports {Dout[14]}]
set_load -pin_load 0 [get_ports {Dout[13]}]
set_load -pin_load 0 [get_ports {Dout[12]}]
set_load -pin_load 0 [get_ports {Dout[11]}]
set_load -pin_load 0 [get_ports {Dout[10]}]
set_load -pin_load 0 [get_ports {Dout[9]}]
set_load -pin_load 0 [get_ports {Dout[8]}]
set_load -pin_load 0 [get_ports {Dout[7]}]
set_load -pin_load 0 [get_ports {Dout[6]}]
set_load -pin_load 0 [get_ports {Dout[5]}]
set_load -pin_load 0 [get_ports {Dout[4]}]
set_load -pin_load 0 [get_ports {Dout[3]}]
set_load -pin_load 0 [get_ports {Dout[2]}]
set_load -pin_load 0 [get_ports {Dout[1]}]
set_load -pin_load 0 [get_ports {Dout[0]}]
create_clock [get_ports CLK]  -period 62.5  -waveform {0 31.25}
set_clock_uncertainty -setup 0  [get_clocks CLK]
set_input_delay -clock CLK  0  [get_ports CLK]
set_input_delay -clock CLK  0  [get_ports {Kin[127]}]
set_input_delay -clock CLK  0  [get_ports {Kin[126]}]
set_input_delay -clock CLK  0  [get_ports {Kin[125]}]
set_input_delay -clock CLK  0  [get_ports {Kin[124]}]
set_input_delay -clock CLK  0  [get_ports {Kin[123]}]
set_input_delay -clock CLK  0  [get_ports {Kin[122]}]
set_input_delay -clock CLK  0  [get_ports {Kin[121]}]
set_input_delay -clock CLK  0  [get_ports {Kin[120]}]
set_input_delay -clock CLK  0  [get_ports {Kin[119]}]
set_input_delay -clock CLK  0  [get_ports {Kin[118]}]
set_input_delay -clock CLK  0  [get_ports {Kin[117]}]
set_input_delay -clock CLK  0  [get_ports {Kin[116]}]
set_input_delay -clock CLK  0  [get_ports {Kin[115]}]
set_input_delay -clock CLK  0  [get_ports {Kin[114]}]
set_input_delay -clock CLK  0  [get_ports {Kin[113]}]
set_input_delay -clock CLK  0  [get_ports {Kin[112]}]
set_input_delay -clock CLK  0  [get_ports {Kin[111]}]
set_input_delay -clock CLK  0  [get_ports {Kin[110]}]
set_input_delay -clock CLK  0  [get_ports {Kin[109]}]
set_input_delay -clock CLK  0  [get_ports {Kin[108]}]
set_input_delay -clock CLK  0  [get_ports {Kin[107]}]
set_input_delay -clock CLK  0  [get_ports {Kin[106]}]
set_input_delay -clock CLK  0  [get_ports {Kin[105]}]
set_input_delay -clock CLK  0  [get_ports {Kin[104]}]
set_input_delay -clock CLK  0  [get_ports {Kin[103]}]
set_input_delay -clock CLK  0  [get_ports {Kin[102]}]
set_input_delay -clock CLK  0  [get_ports {Kin[101]}]
set_input_delay -clock CLK  0  [get_ports {Kin[100]}]
set_input_delay -clock CLK  0  [get_ports {Kin[99]}]
set_input_delay -clock CLK  0  [get_ports {Kin[98]}]
set_input_delay -clock CLK  0  [get_ports {Kin[97]}]
set_input_delay -clock CLK  0  [get_ports {Kin[96]}]
set_input_delay -clock CLK  0  [get_ports {Kin[95]}]
set_input_delay -clock CLK  0  [get_ports {Kin[94]}]
set_input_delay -clock CLK  0  [get_ports {Kin[93]}]
set_input_delay -clock CLK  0  [get_ports {Kin[92]}]
set_input_delay -clock CLK  0  [get_ports {Kin[91]}]
set_input_delay -clock CLK  0  [get_ports {Kin[90]}]
set_input_delay -clock CLK  0  [get_ports {Kin[89]}]
set_input_delay -clock CLK  0  [get_ports {Kin[88]}]
set_input_delay -clock CLK  0  [get_ports {Kin[87]}]
set_input_delay -clock CLK  0  [get_ports {Kin[86]}]
set_input_delay -clock CLK  0  [get_ports {Kin[85]}]
set_input_delay -clock CLK  0  [get_ports {Kin[84]}]
set_input_delay -clock CLK  0  [get_ports {Kin[83]}]
set_input_delay -clock CLK  0  [get_ports {Kin[82]}]
set_input_delay -clock CLK  0  [get_ports {Kin[81]}]
set_input_delay -clock CLK  0  [get_ports {Kin[80]}]
set_input_delay -clock CLK  0  [get_ports {Kin[79]}]
set_input_delay -clock CLK  0  [get_ports {Kin[78]}]
set_input_delay -clock CLK  0  [get_ports {Kin[77]}]
set_input_delay -clock CLK  0  [get_ports {Kin[76]}]
set_input_delay -clock CLK  0  [get_ports {Kin[75]}]
set_input_delay -clock CLK  0  [get_ports {Kin[74]}]
set_input_delay -clock CLK  0  [get_ports {Kin[73]}]
set_input_delay -clock CLK  0  [get_ports {Kin[72]}]
set_input_delay -clock CLK  0  [get_ports {Kin[71]}]
set_input_delay -clock CLK  0  [get_ports {Kin[70]}]
set_input_delay -clock CLK  0  [get_ports {Kin[69]}]
set_input_delay -clock CLK  0  [get_ports {Kin[68]}]
set_input_delay -clock CLK  0  [get_ports {Kin[67]}]
set_input_delay -clock CLK  0  [get_ports {Kin[66]}]
set_input_delay -clock CLK  0  [get_ports {Kin[65]}]
set_input_delay -clock CLK  0  [get_ports {Kin[64]}]
set_input_delay -clock CLK  0  [get_ports {Kin[63]}]
set_input_delay -clock CLK  0  [get_ports {Kin[62]}]
set_input_delay -clock CLK  0  [get_ports {Kin[61]}]
set_input_delay -clock CLK  0  [get_ports {Kin[60]}]
set_input_delay -clock CLK  0  [get_ports {Kin[59]}]
set_input_delay -clock CLK  0  [get_ports {Kin[58]}]
set_input_delay -clock CLK  0  [get_ports {Kin[57]}]
set_input_delay -clock CLK  0  [get_ports {Kin[56]}]
set_input_delay -clock CLK  0  [get_ports {Kin[55]}]
set_input_delay -clock CLK  0  [get_ports {Kin[54]}]
set_input_delay -clock CLK  0  [get_ports {Kin[53]}]
set_input_delay -clock CLK  0  [get_ports {Kin[52]}]
set_input_delay -clock CLK  0  [get_ports {Kin[51]}]
set_input_delay -clock CLK  0  [get_ports {Kin[50]}]
set_input_delay -clock CLK  0  [get_ports {Kin[49]}]
set_input_delay -clock CLK  0  [get_ports {Kin[48]}]
set_input_delay -clock CLK  0  [get_ports {Kin[47]}]
set_input_delay -clock CLK  0  [get_ports {Kin[46]}]
set_input_delay -clock CLK  0  [get_ports {Kin[45]}]
set_input_delay -clock CLK  0  [get_ports {Kin[44]}]
set_input_delay -clock CLK  0  [get_ports {Kin[43]}]
set_input_delay -clock CLK  0  [get_ports {Kin[42]}]
set_input_delay -clock CLK  0  [get_ports {Kin[41]}]
set_input_delay -clock CLK  0  [get_ports {Kin[40]}]
set_input_delay -clock CLK  0  [get_ports {Kin[39]}]
set_input_delay -clock CLK  0  [get_ports {Kin[38]}]
set_input_delay -clock CLK  0  [get_ports {Kin[37]}]
set_input_delay -clock CLK  0  [get_ports {Kin[36]}]
set_input_delay -clock CLK  0  [get_ports {Kin[35]}]
set_input_delay -clock CLK  0  [get_ports {Kin[34]}]
set_input_delay -clock CLK  0  [get_ports {Kin[33]}]
set_input_delay -clock CLK  0  [get_ports {Kin[32]}]
set_input_delay -clock CLK  0  [get_ports {Kin[31]}]
set_input_delay -clock CLK  0  [get_ports {Kin[30]}]
set_input_delay -clock CLK  0  [get_ports {Kin[29]}]
set_input_delay -clock CLK  0  [get_ports {Kin[28]}]
set_input_delay -clock CLK  0  [get_ports {Kin[27]}]
set_input_delay -clock CLK  0  [get_ports {Kin[26]}]
set_input_delay -clock CLK  0  [get_ports {Kin[25]}]
set_input_delay -clock CLK  0  [get_ports {Kin[24]}]
set_input_delay -clock CLK  0  [get_ports {Kin[23]}]
set_input_delay -clock CLK  0  [get_ports {Kin[22]}]
set_input_delay -clock CLK  0  [get_ports {Kin[21]}]
set_input_delay -clock CLK  0  [get_ports {Kin[20]}]
set_input_delay -clock CLK  0  [get_ports {Kin[19]}]
set_input_delay -clock CLK  0  [get_ports {Kin[18]}]
set_input_delay -clock CLK  0  [get_ports {Kin[17]}]
set_input_delay -clock CLK  0  [get_ports {Kin[16]}]
set_input_delay -clock CLK  0  [get_ports {Kin[15]}]
set_input_delay -clock CLK  0  [get_ports {Kin[14]}]
set_input_delay -clock CLK  0  [get_ports {Kin[13]}]
set_input_delay -clock CLK  0  [get_ports {Kin[12]}]
set_input_delay -clock CLK  0  [get_ports {Kin[11]}]
set_input_delay -clock CLK  0  [get_ports {Kin[10]}]
set_input_delay -clock CLK  0  [get_ports {Kin[9]}]
set_input_delay -clock CLK  0  [get_ports {Kin[8]}]
set_input_delay -clock CLK  0  [get_ports {Kin[7]}]
set_input_delay -clock CLK  0  [get_ports {Kin[6]}]
set_input_delay -clock CLK  0  [get_ports {Kin[5]}]
set_input_delay -clock CLK  0  [get_ports {Kin[4]}]
set_input_delay -clock CLK  0  [get_ports {Kin[3]}]
set_input_delay -clock CLK  0  [get_ports {Kin[2]}]
set_input_delay -clock CLK  0  [get_ports {Kin[1]}]
set_input_delay -clock CLK  0  [get_ports {Kin[0]}]
set_input_delay -clock CLK  0  [get_ports {Din[127]}]
set_input_delay -clock CLK  0  [get_ports {Din[126]}]
set_input_delay -clock CLK  0  [get_ports {Din[125]}]
set_input_delay -clock CLK  0  [get_ports {Din[124]}]
set_input_delay -clock CLK  0  [get_ports {Din[123]}]
set_input_delay -clock CLK  0  [get_ports {Din[122]}]
set_input_delay -clock CLK  0  [get_ports {Din[121]}]
set_input_delay -clock CLK  0  [get_ports {Din[120]}]
set_input_delay -clock CLK  0  [get_ports {Din[119]}]
set_input_delay -clock CLK  0  [get_ports {Din[118]}]
set_input_delay -clock CLK  0  [get_ports {Din[117]}]
set_input_delay -clock CLK  0  [get_ports {Din[116]}]
set_input_delay -clock CLK  0  [get_ports {Din[115]}]
set_input_delay -clock CLK  0  [get_ports {Din[114]}]
set_input_delay -clock CLK  0  [get_ports {Din[113]}]
set_input_delay -clock CLK  0  [get_ports {Din[112]}]
set_input_delay -clock CLK  0  [get_ports {Din[111]}]
set_input_delay -clock CLK  0  [get_ports {Din[110]}]
set_input_delay -clock CLK  0  [get_ports {Din[109]}]
set_input_delay -clock CLK  0  [get_ports {Din[108]}]
set_input_delay -clock CLK  0  [get_ports {Din[107]}]
set_input_delay -clock CLK  0  [get_ports {Din[106]}]
set_input_delay -clock CLK  0  [get_ports {Din[105]}]
set_input_delay -clock CLK  0  [get_ports {Din[104]}]
set_input_delay -clock CLK  0  [get_ports {Din[103]}]
set_input_delay -clock CLK  0  [get_ports {Din[102]}]
set_input_delay -clock CLK  0  [get_ports {Din[101]}]
set_input_delay -clock CLK  0  [get_ports {Din[100]}]
set_input_delay -clock CLK  0  [get_ports {Din[99]}]
set_input_delay -clock CLK  0  [get_ports {Din[98]}]
set_input_delay -clock CLK  0  [get_ports {Din[97]}]
set_input_delay -clock CLK  0  [get_ports {Din[96]}]
set_input_delay -clock CLK  0  [get_ports {Din[95]}]
set_input_delay -clock CLK  0  [get_ports {Din[94]}]
set_input_delay -clock CLK  0  [get_ports {Din[93]}]
set_input_delay -clock CLK  0  [get_ports {Din[92]}]
set_input_delay -clock CLK  0  [get_ports {Din[91]}]
set_input_delay -clock CLK  0  [get_ports {Din[90]}]
set_input_delay -clock CLK  0  [get_ports {Din[89]}]
set_input_delay -clock CLK  0  [get_ports {Din[88]}]
set_input_delay -clock CLK  0  [get_ports {Din[87]}]
set_input_delay -clock CLK  0  [get_ports {Din[86]}]
set_input_delay -clock CLK  0  [get_ports {Din[85]}]
set_input_delay -clock CLK  0  [get_ports {Din[84]}]
set_input_delay -clock CLK  0  [get_ports {Din[83]}]
set_input_delay -clock CLK  0  [get_ports {Din[82]}]
set_input_delay -clock CLK  0  [get_ports {Din[81]}]
set_input_delay -clock CLK  0  [get_ports {Din[80]}]
set_input_delay -clock CLK  0  [get_ports {Din[79]}]
set_input_delay -clock CLK  0  [get_ports {Din[78]}]
set_input_delay -clock CLK  0  [get_ports {Din[77]}]
set_input_delay -clock CLK  0  [get_ports {Din[76]}]
set_input_delay -clock CLK  0  [get_ports {Din[75]}]
set_input_delay -clock CLK  0  [get_ports {Din[74]}]
set_input_delay -clock CLK  0  [get_ports {Din[73]}]
set_input_delay -clock CLK  0  [get_ports {Din[72]}]
set_input_delay -clock CLK  0  [get_ports {Din[71]}]
set_input_delay -clock CLK  0  [get_ports {Din[70]}]
set_input_delay -clock CLK  0  [get_ports {Din[69]}]
set_input_delay -clock CLK  0  [get_ports {Din[68]}]
set_input_delay -clock CLK  0  [get_ports {Din[67]}]
set_input_delay -clock CLK  0  [get_ports {Din[66]}]
set_input_delay -clock CLK  0  [get_ports {Din[65]}]
set_input_delay -clock CLK  0  [get_ports {Din[64]}]
set_input_delay -clock CLK  0  [get_ports {Din[63]}]
set_input_delay -clock CLK  0  [get_ports {Din[62]}]
set_input_delay -clock CLK  0  [get_ports {Din[61]}]
set_input_delay -clock CLK  0  [get_ports {Din[60]}]
set_input_delay -clock CLK  0  [get_ports {Din[59]}]
set_input_delay -clock CLK  0  [get_ports {Din[58]}]
set_input_delay -clock CLK  0  [get_ports {Din[57]}]
set_input_delay -clock CLK  0  [get_ports {Din[56]}]
set_input_delay -clock CLK  0  [get_ports {Din[55]}]
set_input_delay -clock CLK  0  [get_ports {Din[54]}]
set_input_delay -clock CLK  0  [get_ports {Din[53]}]
set_input_delay -clock CLK  0  [get_ports {Din[52]}]
set_input_delay -clock CLK  0  [get_ports {Din[51]}]
set_input_delay -clock CLK  0  [get_ports {Din[50]}]
set_input_delay -clock CLK  0  [get_ports {Din[49]}]
set_input_delay -clock CLK  0  [get_ports {Din[48]}]
set_input_delay -clock CLK  0  [get_ports {Din[47]}]
set_input_delay -clock CLK  0  [get_ports {Din[46]}]
set_input_delay -clock CLK  0  [get_ports {Din[45]}]
set_input_delay -clock CLK  0  [get_ports {Din[44]}]
set_input_delay -clock CLK  0  [get_ports {Din[43]}]
set_input_delay -clock CLK  0  [get_ports {Din[42]}]
set_input_delay -clock CLK  0  [get_ports {Din[41]}]
set_input_delay -clock CLK  0  [get_ports {Din[40]}]
set_input_delay -clock CLK  0  [get_ports {Din[39]}]
set_input_delay -clock CLK  0  [get_ports {Din[38]}]
set_input_delay -clock CLK  0  [get_ports {Din[37]}]
set_input_delay -clock CLK  0  [get_ports {Din[36]}]
set_input_delay -clock CLK  0  [get_ports {Din[35]}]
set_input_delay -clock CLK  0  [get_ports {Din[34]}]
set_input_delay -clock CLK  0  [get_ports {Din[33]}]
set_input_delay -clock CLK  0  [get_ports {Din[32]}]
set_input_delay -clock CLK  0  [get_ports {Din[31]}]
set_input_delay -clock CLK  0  [get_ports {Din[30]}]
set_input_delay -clock CLK  0  [get_ports {Din[29]}]
set_input_delay -clock CLK  0  [get_ports {Din[28]}]
set_input_delay -clock CLK  0  [get_ports {Din[27]}]
set_input_delay -clock CLK  0  [get_ports {Din[26]}]
set_input_delay -clock CLK  0  [get_ports {Din[25]}]
set_input_delay -clock CLK  0  [get_ports {Din[24]}]
set_input_delay -clock CLK  0  [get_ports {Din[23]}]
set_input_delay -clock CLK  0  [get_ports {Din[22]}]
set_input_delay -clock CLK  0  [get_ports {Din[21]}]
set_input_delay -clock CLK  0  [get_ports {Din[20]}]
set_input_delay -clock CLK  0  [get_ports {Din[19]}]
set_input_delay -clock CLK  0  [get_ports {Din[18]}]
set_input_delay -clock CLK  0  [get_ports {Din[17]}]
set_input_delay -clock CLK  0  [get_ports {Din[16]}]
set_input_delay -clock CLK  0  [get_ports {Din[15]}]
set_input_delay -clock CLK  0  [get_ports {Din[14]}]
set_input_delay -clock CLK  0  [get_ports {Din[13]}]
set_input_delay -clock CLK  0  [get_ports {Din[12]}]
set_input_delay -clock CLK  0  [get_ports {Din[11]}]
set_input_delay -clock CLK  0  [get_ports {Din[10]}]
set_input_delay -clock CLK  0  [get_ports {Din[9]}]
set_input_delay -clock CLK  0  [get_ports {Din[8]}]
set_input_delay -clock CLK  0  [get_ports {Din[7]}]
set_input_delay -clock CLK  0  [get_ports {Din[6]}]
set_input_delay -clock CLK  0  [get_ports {Din[5]}]
set_input_delay -clock CLK  0  [get_ports {Din[4]}]
set_input_delay -clock CLK  0  [get_ports {Din[3]}]
set_input_delay -clock CLK  0  [get_ports {Din[2]}]
set_input_delay -clock CLK  0  [get_ports {Din[1]}]
set_input_delay -clock CLK  0  [get_ports {Din[0]}]
set_input_delay -clock CLK  0  [get_ports EN]
set_input_delay -clock CLK  0  [get_ports RSTn]
set_output_delay -clock CLK  0  [get_ports {Dout[127]}]
set_output_delay -clock CLK  0  [get_ports {Dout[126]}]
set_output_delay -clock CLK  0  [get_ports {Dout[125]}]
set_output_delay -clock CLK  0  [get_ports {Dout[124]}]
set_output_delay -clock CLK  0  [get_ports {Dout[123]}]
set_output_delay -clock CLK  0  [get_ports {Dout[122]}]
set_output_delay -clock CLK  0  [get_ports {Dout[121]}]
set_output_delay -clock CLK  0  [get_ports {Dout[120]}]
set_output_delay -clock CLK  0  [get_ports {Dout[119]}]
set_output_delay -clock CLK  0  [get_ports {Dout[118]}]
set_output_delay -clock CLK  0  [get_ports {Dout[117]}]
set_output_delay -clock CLK  0  [get_ports {Dout[116]}]
set_output_delay -clock CLK  0  [get_ports {Dout[115]}]
set_output_delay -clock CLK  0  [get_ports {Dout[114]}]
set_output_delay -clock CLK  0  [get_ports {Dout[113]}]
set_output_delay -clock CLK  0  [get_ports {Dout[112]}]
set_output_delay -clock CLK  0  [get_ports {Dout[111]}]
set_output_delay -clock CLK  0  [get_ports {Dout[110]}]
set_output_delay -clock CLK  0  [get_ports {Dout[109]}]
set_output_delay -clock CLK  0  [get_ports {Dout[108]}]
set_output_delay -clock CLK  0  [get_ports {Dout[107]}]
set_output_delay -clock CLK  0  [get_ports {Dout[106]}]
set_output_delay -clock CLK  0  [get_ports {Dout[105]}]
set_output_delay -clock CLK  0  [get_ports {Dout[104]}]
set_output_delay -clock CLK  0  [get_ports {Dout[103]}]
set_output_delay -clock CLK  0  [get_ports {Dout[102]}]
set_output_delay -clock CLK  0  [get_ports {Dout[101]}]
set_output_delay -clock CLK  0  [get_ports {Dout[100]}]
set_output_delay -clock CLK  0  [get_ports {Dout[99]}]
set_output_delay -clock CLK  0  [get_ports {Dout[98]}]
set_output_delay -clock CLK  0  [get_ports {Dout[97]}]
set_output_delay -clock CLK  0  [get_ports {Dout[96]}]
set_output_delay -clock CLK  0  [get_ports {Dout[95]}]
set_output_delay -clock CLK  0  [get_ports {Dout[94]}]
set_output_delay -clock CLK  0  [get_ports {Dout[93]}]
set_output_delay -clock CLK  0  [get_ports {Dout[92]}]
set_output_delay -clock CLK  0  [get_ports {Dout[91]}]
set_output_delay -clock CLK  0  [get_ports {Dout[90]}]
set_output_delay -clock CLK  0  [get_ports {Dout[89]}]
set_output_delay -clock CLK  0  [get_ports {Dout[88]}]
set_output_delay -clock CLK  0  [get_ports {Dout[87]}]
set_output_delay -clock CLK  0  [get_ports {Dout[86]}]
set_output_delay -clock CLK  0  [get_ports {Dout[85]}]
set_output_delay -clock CLK  0  [get_ports {Dout[84]}]
set_output_delay -clock CLK  0  [get_ports {Dout[83]}]
set_output_delay -clock CLK  0  [get_ports {Dout[82]}]
set_output_delay -clock CLK  0  [get_ports {Dout[81]}]
set_output_delay -clock CLK  0  [get_ports {Dout[80]}]
set_output_delay -clock CLK  0  [get_ports {Dout[79]}]
set_output_delay -clock CLK  0  [get_ports {Dout[78]}]
set_output_delay -clock CLK  0  [get_ports {Dout[77]}]
set_output_delay -clock CLK  0  [get_ports {Dout[76]}]
set_output_delay -clock CLK  0  [get_ports {Dout[75]}]
set_output_delay -clock CLK  0  [get_ports {Dout[74]}]
set_output_delay -clock CLK  0  [get_ports {Dout[73]}]
set_output_delay -clock CLK  0  [get_ports {Dout[72]}]
set_output_delay -clock CLK  0  [get_ports {Dout[71]}]
set_output_delay -clock CLK  0  [get_ports {Dout[70]}]
set_output_delay -clock CLK  0  [get_ports {Dout[69]}]
set_output_delay -clock CLK  0  [get_ports {Dout[68]}]
set_output_delay -clock CLK  0  [get_ports {Dout[67]}]
set_output_delay -clock CLK  0  [get_ports {Dout[66]}]
set_output_delay -clock CLK  0  [get_ports {Dout[65]}]
set_output_delay -clock CLK  0  [get_ports {Dout[64]}]
set_output_delay -clock CLK  0  [get_ports {Dout[63]}]
set_output_delay -clock CLK  0  [get_ports {Dout[62]}]
set_output_delay -clock CLK  0  [get_ports {Dout[61]}]
set_output_delay -clock CLK  0  [get_ports {Dout[60]}]
set_output_delay -clock CLK  0  [get_ports {Dout[59]}]
set_output_delay -clock CLK  0  [get_ports {Dout[58]}]
set_output_delay -clock CLK  0  [get_ports {Dout[57]}]
set_output_delay -clock CLK  0  [get_ports {Dout[56]}]
set_output_delay -clock CLK  0  [get_ports {Dout[55]}]
set_output_delay -clock CLK  0  [get_ports {Dout[54]}]
set_output_delay -clock CLK  0  [get_ports {Dout[53]}]
set_output_delay -clock CLK  0  [get_ports {Dout[52]}]
set_output_delay -clock CLK  0  [get_ports {Dout[51]}]
set_output_delay -clock CLK  0  [get_ports {Dout[50]}]
set_output_delay -clock CLK  0  [get_ports {Dout[49]}]
set_output_delay -clock CLK  0  [get_ports {Dout[48]}]
set_output_delay -clock CLK  0  [get_ports {Dout[47]}]
set_output_delay -clock CLK  0  [get_ports {Dout[46]}]
set_output_delay -clock CLK  0  [get_ports {Dout[45]}]
set_output_delay -clock CLK  0  [get_ports {Dout[44]}]
set_output_delay -clock CLK  0  [get_ports {Dout[43]}]
set_output_delay -clock CLK  0  [get_ports {Dout[42]}]
set_output_delay -clock CLK  0  [get_ports {Dout[41]}]
set_output_delay -clock CLK  0  [get_ports {Dout[40]}]
set_output_delay -clock CLK  0  [get_ports {Dout[39]}]
set_output_delay -clock CLK  0  [get_ports {Dout[38]}]
set_output_delay -clock CLK  0  [get_ports {Dout[37]}]
set_output_delay -clock CLK  0  [get_ports {Dout[36]}]
set_output_delay -clock CLK  0  [get_ports {Dout[35]}]
set_output_delay -clock CLK  0  [get_ports {Dout[34]}]
set_output_delay -clock CLK  0  [get_ports {Dout[33]}]
set_output_delay -clock CLK  0  [get_ports {Dout[32]}]
set_output_delay -clock CLK  0  [get_ports {Dout[31]}]
set_output_delay -clock CLK  0  [get_ports {Dout[30]}]
set_output_delay -clock CLK  0  [get_ports {Dout[29]}]
set_output_delay -clock CLK  0  [get_ports {Dout[28]}]
set_output_delay -clock CLK  0  [get_ports {Dout[27]}]
set_output_delay -clock CLK  0  [get_ports {Dout[26]}]
set_output_delay -clock CLK  0  [get_ports {Dout[25]}]
set_output_delay -clock CLK  0  [get_ports {Dout[24]}]
set_output_delay -clock CLK  0  [get_ports {Dout[23]}]
set_output_delay -clock CLK  0  [get_ports {Dout[22]}]
set_output_delay -clock CLK  0  [get_ports {Dout[21]}]
set_output_delay -clock CLK  0  [get_ports {Dout[20]}]
set_output_delay -clock CLK  0  [get_ports {Dout[19]}]
set_output_delay -clock CLK  0  [get_ports {Dout[18]}]
set_output_delay -clock CLK  0  [get_ports {Dout[17]}]
set_output_delay -clock CLK  0  [get_ports {Dout[16]}]
set_output_delay -clock CLK  0  [get_ports {Dout[15]}]
set_output_delay -clock CLK  0  [get_ports {Dout[14]}]
set_output_delay -clock CLK  0  [get_ports {Dout[13]}]
set_output_delay -clock CLK  0  [get_ports {Dout[12]}]
set_output_delay -clock CLK  0  [get_ports {Dout[11]}]
set_output_delay -clock CLK  0  [get_ports {Dout[10]}]
set_output_delay -clock CLK  0  [get_ports {Dout[9]}]
set_output_delay -clock CLK  0  [get_ports {Dout[8]}]
set_output_delay -clock CLK  0  [get_ports {Dout[7]}]
set_output_delay -clock CLK  0  [get_ports {Dout[6]}]
set_output_delay -clock CLK  0  [get_ports {Dout[5]}]
set_output_delay -clock CLK  0  [get_ports {Dout[4]}]
set_output_delay -clock CLK  0  [get_ports {Dout[3]}]
set_output_delay -clock CLK  0  [get_ports {Dout[2]}]
set_output_delay -clock CLK  0  [get_ports {Dout[1]}]
set_output_delay -clock CLK  0  [get_ports {Dout[0]}]
